# Generated by Django 3.2.8 on 2022-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220919_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(default=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
