# Generated by Django 3.2.8 on 2022-09-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
