# Generated by Django 3.2.8 on 2022-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20221003_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(null=True, upload_to='Posted_Images'),
        ),
    ]
